"""Chain Event Graph schemas.

A Chain Event Graph (CEG) is a graphical representation of a sequence of
events with conditional probabilities on transitions, generalising
Bayesian networks for asymmetric event processes (Smith, Anderson 2008).

In this pipeline, a CEG is generated by a downstream LLM from the
top-ranked hypothesis. The graph is later validated structurally
(connected, DAG, probabilities sum to 1 at each node) and rendered to SVG.

Schemas here intentionally do not enforce structural constraints — those
live in `consortium.ceg.validator`. Schema validation here is only
field-level (types, ranges, required fields, enum membership).
"""
from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class CEGNodeType(str, Enum):
    ROOT = "root"
    SITUATION = "situation"
    LEAF = "leaf"


class CEGNode(BaseModel):
    """A node in the CEG, representing a state of the world."""

    model_config = ConfigDict(use_enum_values=True, extra="forbid")

    id: str = Field(..., description="Stable identifier, e.g. 'N0'.")
    type: CEGNodeType
    description: str = Field(..., description="What state of the world this node represents.")
    associated_evidence: list[str] = Field(
        default_factory=list,
        description="Evidence IDs that anchor this state.",
    )


class CEGEdge(BaseModel):
    """A directed edge in the CEG, representing a transition (event)."""

    model_config = ConfigDict(extra="forbid")

    id: str = Field(..., description="Stable identifier, e.g. 'T0'.")
    from_node: str = Field(..., description="ID of source node.")
    to_node: str = Field(..., description="ID of destination node.")
    event_label: str = Field(..., description="A short label for the transition event.")
    conditional_probability: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description=(
            "P(to_node | from_node). Outgoing edges from any single node should "
            "sum to 1.0; this is enforced by the validator, not at schema level."
        ),
    )
    associated_evidence: list[str] = Field(default_factory=list)


class CEGStage(BaseModel):
    """An equivalence class of nodes that share identical outgoing transition probabilities.

    Stages are the defining feature distinguishing CEGs from event trees.
    For the POC the consortium may produce a graph with trivial staging
    (one node per stage); a follow-up pass may collapse equivalent nodes.
    """

    model_config = ConfigDict(extra="forbid")

    id: str = Field(..., description="Stable identifier, e.g. 'S0'.")
    member_nodes: list[str] = Field(
        ..., min_length=1, description="IDs of nodes in this stage."
    )
    rationale: Optional[str] = Field(
        None, description="Why these nodes share a stage."
    )


class ChainEventGraph(BaseModel):
    """A CEG built from a single hypothesis."""

    model_config = ConfigDict(extra="forbid")

    case_id: str
    hypothesis_id: str = Field(
        ..., description="The Hypothesis this CEG materialises."
    )

    nodes: list[CEGNode]
    edges: list[CEGEdge]
    stages: list[CEGStage] = Field(default_factory=list)

    root_node_id: str = Field(..., description="Must appear in nodes; must be of type root.")
    leaf_node_ids: list[str] = Field(
        ..., min_length=1, description="Must all appear in nodes; all must be of type leaf."
    )

    notes: Optional[str] = None